#    Numpy Tutorial

In [7]:
import numpy as np

a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print(a)

b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(type(b))
print(b[0,0], b[0,1], b[0,2])

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
<class 'numpy.ndarray'>
1 2 3


In [4]:
import numpy as np

print(np.zeros((1,2)))
print(np.random.random((3,3)))


[[ 0.  0.]]
[[ 0.17321291  0.51488853  0.39770476]
 [ 0.67342015  0.7830224   0.01993673]
 [ 0.21872366  0.26848537  0.68180676]]
